In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('소상공인_220630/소상공인시장진흥공단_상가(상권)정보_서울_202206.csv', encoding='utf-8')
df.head(2)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23324279,제중건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1156010600100410002034626,NaN,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,NaN,1,NaN,126.907168,37.520613
1,24525909,민속악기사,NaN,D,소매,D04,취미/오락관련소매,D04A09,악기판매,G47593,...,1120012200101420011000227,NaN,서울특별시 성동구 용답5길 2,133849,4803.0,NaN,NaN,NaN,127.049018,37.566857

In [18]:
df['구'] = df['도로명주소'].apply(lambda x : x.split()[1])

In [19]:
df['구'].value_counts()

강남구     33454
송파구     21050
서초구     20069
강서구     17182
마포구     16740
중구      16599
영등포구    14987
종로구     14258
강동구     14004
광진구     13529
구로구     13008
관악구     12606
동대문구    12550
은평구     12094
양천구     11960
노원구     11903
성북구     11872
중랑구     11107
용산구     11022
성동구     10672
금천구      9715
동작구      9573
서대문구     9444
강북구      8877
도봉구      7954
Name: 구, dtype: int64

In [31]:
new_df = df[(df['구']=='영등포구') & (df['상권업종대분류명']=='음식')]

In [33]:
new_df.to_csv('영등포구_음식점_상가정보.csv', encoding='utf-8-sig')

In [27]:
df[df['상권업종대분류명']=='음식']

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도,구
4,17174175,비지트,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,상랑의빌딩,서울특별시 서초구 동광로18길 82,137837,6572.0,NaN,1,NaN,126.991394,37.488375,서초구
5,17174119,쓰리에프,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,NaN,서울특별시 동작구 동작대로27가길 12,156816,7008.0,NaN,NaN,NaN,126.980952,37.487105,동작구
6,17174040,다향,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,NaN,서울특별시 서초구 효령로 230,137869,6709.0,NaN,1,NaN,127.009382,37.483436,서초구
7,25530299,고향생막걸리,NaN,Q,음식,Q09,유흥주점,Q09A04,민속주점,I56219,...,코끼리상가,서울특별시 강남구 압구정로 216,135894,6023.0,NaN,1,NaN,127.031012,37.528073,강남구
12,17163092,도전최강달인왕만두,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,고덕그라시움,서울특별시 강동구 고덕로 353,134082,5224.0,NaN,NaN,NaN,127.159471,37.556197,강동구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346210,18450530,샐럽스프진관점,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,휴먼프라자I,서울특별시 은평구 진관2로 19,122200,3306.0,NaN,1,NaN,126.919569,37.634843,은평구
346217,18445536,도너츠윤,덕성여대점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,NaN,서울특별시 강북구 삼양로 530,142892,1044.0,NaN,1,NaN,127.013504,37.650317,강북구
346221,18453167,텐,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,목동슬로우스퀘어,서울특별시 양천구 오목로 345,158716,7999.0,NaN,NaN,NaN,126.875815,37.524734,양천구
346225,18455989,석정칼국수,NaN,Q,음식,Q04,분식,Q04A02,국수/만두/칼국수,I56194,...,NaN,서울특별시 중랑구 면목로 446,131817,2160.0,NaN,1,NaN,127.086895,37.591754,중랑구
346226,18454507,서울왕도숯불갈비,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,NaN,서울특별시 동대문구 약령시로 122-3,130862,2573.0,NaN,NaN,NaN,127.043357,37.582867,동대문구

In [7]:
df_filter = df[df.상권업종대분류명=='음식'].iloc[:, 0:11]
df_filter.상권업종소분류명.value_counts()

한식/백반/한정식      27426
커피전문점/카페/다방    19494
호프/맥주           5811
라면김밥분식          5612
후라이드/양념치킨       4179
               ...
유산균아이스크림전문         2
해물부페               2
락카페                2
징기스칸요리전문           1
재첩국전문              1
Name: 상권업종소분류명, Length: 115, dtype: int64